export { default as Home } from './Home';
export { default as HomeInfoBox } from './HomeInfoBox';
export { default as HomeIntroBox } from './HomeIntroBox';
export { default as HomeRelated } from './HomeRelated';
export { default as HomeCategories } from './HomeCategories';
export { default as About } from './About';
export { default as Blog } from './Blog';
export { default as Contact } from './Contact';
export { default as Header } from './Header';
